### ISSUE TITLE
tW Navigation

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/gateway-edit#3]
Since tW can have multiple checks per verse, as a user, I want to be able to navigate (one by one, or in a list) from one check to the next within a particular resource card. As I navigate, the associated word in the scripture pane should be highlighted (currently selected words turn blue). An associated TW card should show the content of the currently selected TW article. (Links inside the article do not need to open for the MVP. See #12).

- [ ] Show [TWL](https://git.door43.org/unfoldingWord/en_twl) in a one by one view
- [ ] Show TWL in a table (TW title | OL Quote)
- [ ] The currently selected TWL record highlights a word in the scripture pane(s)
- [ ] The TW card updates to show the TW article for the current TWL record

**Comment by birchamp** [comment]
mockup of TSV table view:
![Screen Shot 2020-12-03 at 10.45.53 AM.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/b5dd215b-5e4e-464d-b870-04a9b5873ce3)

**Comment by birchamp** [comment]
The latest TWL is here: https://git.door43.org/unfoldingWord/en_twl
