### ISSUE TITLE
EPIC: Move Word Alignment UI from tCore into RCL

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/gateway-edit#360]
Pull Word Alignment UI from translationCore and wrap in RCL

**MVP:**
- [x] remove redux - used in wordmap predictions
- [ ] compatibility with newer react and newer apps:
  - [x] replace react-dnd with html5 drag/drop
  - [x] remove material UI dependencies for maximum compatibility
- [x] wrap converted code in RCL
- [x] add styleguidist examples

**Future Enhancements:**
- [ ] add compatibility with alignment APIs:
  - [ ] compatibility with proskoma edit.
- [ ] make headless
  - [ ] convert components to Hooks
  - [ ] create custom hooks for each component's business logic

**Comment by birchamp** [comment]
@kintsoogi @PhotoNomad0 Goal this is to shift it to an Epic about integrating this RCL into gE.
