### ISSUE TITLE
Brainstorm and refine a checklist for what a easily reusable library (or component) should be.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-edit#430]
Answer the question: What does an easily reusable component library look like?
Documentation :
- UI/UX manager- To include it or not? React/MUI dependent. MonoRepo.
- Isolation of component based on the layers: Application/ Framework/Language/Data-view
- 

RCLs to look at as an example :
- TranslationHelps
- DatatableTranslatable

**Comment by mandolyte** [comment]
After some thought, I notice that there are two different objectives stated. And the two things are not the same. These are: 
- Fully reusable (in the title of the issue)
- Easily reusable (in the body of the issue)

To be fully reusable (in web and node apps) would lead us to web components that are framework agnostic because they are just HTML elements like `<p>`. Just custom designed and implemented.

To be easily reusable is slightly different. Of course, a fully reusable component is also easily used. But if we limit ourselves to the commonly used framework, namely, React (and the frameworks that extend it, such as Next.js) then our task is easier. Easier because we can ignore Svelte, Vue, Angular, etc.

**Comment by mandolyte** [comment]
# Checklist for Ease of Reuse

This will be a checklist for *easily* reusing a component library. A *library* may expose multiple, related components.

## Scope

- Reusability will be limited to React applications and React-based frameworks, such as Next.js.

## Prerequisites

1. NPM will be used as the reuse-infrastructure.
2. Semver will be used to signal the kinds of changes over time made to the component,
3. The language will be JavaScript or TypeScript.
4. Dependencies will kept to a minimum to minimize impact on size and performance of apps using the component

## Outstanding Questions

1. Use of Material-UI: does it meet prerequisite 4?
2. Use of Tailwind: does it meet prerequisite 4?
3. Type safety is widely considered a critical aspect of ease of reuse. Plus IDE's will enforce type safety so that mistakes are prevented at edit time. This would suggest that we use TypeScript as the preferred language. This deserves some discussion!
4. Documentation options:
	- Styleguidist (or other doc tool)
	- Example folder with instructions on how to run locally
	- Examples built with code sandbox or stackblitz
	- Some combination of the above

## Checklist

- [ ] Component built using functions, not classes.
- [ ] Clear and documented API (with type definitions as needed for TypeScript).
- [ ] Complete examples showing use of the entire API (see OQ#4).
- [ ] Minimal use of external dependencies.
- [ ] For required external dependencies (such as React, MUI, etc.):
	- [ ] Document tested versions (and combination of versions if needed)
	- [ ] Use of "peer" dependencies to let app chose versions (ie, avoid mixing different versions of library in the same app)
- [ ] Do not rely on "tree-shaking" to prune unused code in the library. Instead, make each library component directly accessible.

**Comment by mandolyte** [comment]
Above now in gdocs for collaboration.
