### ISSUE TITLE
Add checklist of cards to merge in merge dialog

### ISSUE THREAD

**Issue by kintsoogi** [unfoldingWord/gateway-edit#457]
### Background / Story
Right now when we select "Merge my work" from the hamburger menu, it merges all cards that are have changes and are able to merge. Instead, we would like to give the user a checklist of cards to merge. The card should be displayed in the checklist if:
- [ ] Card does not have any conflicts or errors
- [ ] Card has changes (there exists a user branch for the card)
- [ ] Card is read to merge

If these conditions are not true, the card should not be displayed in the checkbox. The user selects which cards on the checkbox that they would like to merge, and then when the user clicks "submit", ONLY those selected cards should have their changes merged to master. It would probably be helpful if the checkboxes were preselected, so that the user can unselect instead of having to select every one. 

### Implementation Tips (@jincypjose)

The **MergeDialog** component in **transation-helps-rcl** is where the checkbox should exist
The **useMergeCardProps** hook takes in the merge status for the cards and creates an object of lists of cards with erros, conflicts, those that are mergeable, etc. 
This is where the information to use to create the checkboxes would be

### Definition of Done 
- [ ] In the merge dialog, a checkbox list of mergeable cards is shown
- [ ] A user is able to select and deselect which cards they would like to merge
- [ ] When the user clicks submit, only the selected card changes are merged to master

**Comment by danielklapp** [comment]
In the merge dialog, a checkbox list for seven out of eight mergeable cards is shown. Text for translationWords Article line is not shown.

<img width="1440" alt="Screenshot 2023-07-24 at 10 07 36 PM" src="https://github.com/unfoldingWord/gateway-edit/assets/82067076/78e85252-e095-4fdd-a43d-fb475fb4348b">

**Comment by danielklapp** [comment]
I wrote up a new issue about Cards Sync Feedback showing ugnt and uhb under Cards With No Changes To Save#510 and put it in QA fail.

**Comment by elsylambert** [comment]
Looks good in v2.1.0 build 66dd56e QA.  Resource cards that have edits saved, are listed when Merge my work is chosen from the Menu. Users can choose the resources by checking the boxes and those  user branch for those resources gets merged to master branch and gets deleted. The merged Resource is no longer available in the checklist until the next edits are done.

**Comment by danielklapp** [comment]
Checkbox list looks good, all eight mergeable cards are shown. Users are able to select and deselect which cards they would like to merge. Only the selected cards are merged to master, whether one, two, and etc. Tested with v2.1.0 build 66dd56e QA.
