### ISSUE TITLE
Scripture Navigation

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/gateway-edit#5]
As a user I want to able to navigate scriptures as follows:
1. Navigate between available books and then select a particular book. Once the book is selected, display chapter 1 and verse 1 of the book and all related translation helps available for that particular BCV. 
2. Should be able to switch to different chapters and/or verses within a book. Explicitly changing chapters will default to verse 1.
3. (Not MVP see:#13 ) Should be able to scroll across verses within a preselected range of CV (ex: 10 verses /1 chapter / 3 chapters). default range would be single chapter.
4.(Not MVP) Scrolling and clicking on a different Chapter and verse (CV)than the current selected CV should update the navigation and all related resources to the clicked CV.

So that I am able to check across different verses and books for the purpose of harmonization.

- [ ] Change book, chapter, and verse numbers in the navigation bar
- [ ] Default to CV 1:1 for book change
- [ ] Default to V 1 for Chapter change
- [ ] Update all resources/helps on BCV change
